version: '3'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/lottery
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lottery
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: